Add homestead stats, change port number and add in accumulator with count stats

diff --git a/debian/clearwater-snmp-handler-homestead.postinst b/debian/clearwater-snmp-handler-homestead.postinst
--- a/debian/clearwater-snmp-handler-homestead.postinst
+++ b/debian/clearwater-snmp-handler-homestead.postinst
@@ -1,6 +1,9 @@
+#!/bin/sh
+
+# @file clearwater-snmpd.postinst
 #
 # Project Clearwater - IMS in the Cloud
-# Copyright (C) 2013 Metaswitch Networks Ltd
+# Copyright (C) 2013  Metaswitch Networks Ltd
 #
 # This program is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -9,16 +12,16 @@
 # the program along with SSL, set forth below. This program is distributed
 # in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 # without even the implied warranty of MERCHANTABILITY or FITNESS FOR
-# A PARTICULAR PURPOSE. See the GNU General Public License for more
+# A PARTICULAR PURPOSE.  See the GNU General Public License for more
 # details. You should have received a copy of the GNU General Public
-# License along with this program. If not, see
+# License along with this program.  If not, see
 # <http://www.gnu.org/licenses/>.
 #
 # The author can be reached by email at clearwater@metaswitch.com or by
 # post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
 #
 # Special Exception
-# Metaswitch Networks Ltd grants you permission to copy, modify,
+# Metaswitch Networks Ltd  grants you permission to copy, modify,
 # propagate, and distribute a work formed by combining OpenSSL with The
 # Software, or a work derivative of such a combination, even if such
 # copying, modification, propagation, or distribution would otherwise
@@ -31,29 +34,40 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
+#
+# see: dh_installdeb(1)
 
-# this should come first so make does the right thing by default
-all: deb
+set -e
 
-sprout_handler.so: *.cpp *.hpp
-	g++ `net-snmp-config --cflags` -Wall -std=c++0x -g -O0 -fPIC -shared -o sprout_handler.so custom_handler.cpp oid.cpp oidtree.cpp sproutdata.cpp zmq_listener.cpp zmq_message_handler.cpp `net-snmp-config --libs` -lzmq -lpthread
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-bono_handler.so: *.cpp *.hpp
-	g++ `net-snmp-config --cflags` -Wall -std=c++0x -g -O0 -fPIC -shared -o bono_handler.so custom_handler.cpp oid.cpp oidtree.cpp bonodata.cpp zmq_listener.cpp zmq_message_handler.cpp `net-snmp-config --libs` -lzmq -lpthread
+case "$1" in
+    configure)
+        service snmpd restart || true
+    ;;
 
-homestead_handler.so: *.cpp *.hpp
-	g++ `net-snmp-config --cflags` -Wall -std=c++0x -g -O0 -fPIC -shared -o homestead_handler.so custom_handler.cpp oid.cpp oidtree.cpp homesteaddata.cpp zmq_listener.cpp zmq_message_handler.cpp `net-snmp-config --libs` -lzmq -lpthread
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
 
-# Makefile for Clearwater infrastructure packages
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
-DEB_COMPONENT := clearwater-snmp-handlers
-DEB_MAJOR_VERSION := 1.0
-DEB_NAMES := clearwater-snmp-handler-bono clearwater-snmp-handler-sprout clearwater-snmp-handler-homestead
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
-include build-infra/cw-deb.mk
+#DEBHELPER#
 
-.PHONY: deb
-deb: sprout_handler.so bono_handler.so homestead_handler.so deb-only
-
-.PHONY: all deb-only deb
-
+exit 0
